- name: Add gitlab repo
  shell: curl -LJO https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb && dpkg -i gitlab-runner_amd64.deb

- name: gitlab runner register
  shell: gitlab-runner register \
    --non-interactive \
    --url {{ gitlab.url }} \
    --registration-token {{ gitlab.registration_token }} \
    --description {{ gitlab.runner_name }} \
    --executor shell \
    --tag-list "nextjs,react" \